name: Publish Blazor App to GitHub Pages

on: [ push, workflow_dispatch ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_test_artifact:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'

    - name: Restore NuGet packages
      run: dotnet restore .

    - name: Build solution
      run: dotnet build .

    - name: Test solution
      run: dotnet test . -c Release

    - name: Publish artifact
      run: dotnet publish src/BlazorApp -c Release -o published

    - name: Set file permissions
      run: chmod -R 744 published/wwwroot

    - name: Upload artifact for web
      uses: actions/upload-pages-artifact@v1
      with:
        path: published/wwwroot

  deploy:
    name: Deploy App to GitHub Pages
    needs: build_test_artifact
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
